# Generated by Django 3.0.8 on 2020-07-30 13:29

import charities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_auto_20200730_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='reg_number',
            field=models.CharField(max_length=10, validators=[charities.validators.RegNumberValidator()]),
        ),
    ]
