# Generated by Django 3.0.8 on 2020-09-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_auto_20200808_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='gender_limit',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MF', 'Unset')], default='MF', max_length=2),
        ),
    ]
