# Generated by Django 3.0.8 on 2020-07-30 13:29

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200728_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[accounts.validators.PhoneValidator()]),
        ),
    ]
